main: nl.dantevg.webstatsstorer.WebStatsStorer
name: WebStatsStorer
version: 1.0.0
api-version: 1.13
description: Store WebStats data
author: RedPolygon
depend: [WebStats]
commands: 
  storestats:
    description: Store WebStats data
